name: deploy
on:
  workflow_run:
    workflows: ["Test on main"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
      - name: change directory
        run: cd /home/user/php-parser
      - name: pull the changes
        run: git pull
      - name: composer install
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: run test
        run: composer test
